feat: biometrics authentication
desmos-labs/dpm pull request #86
Opened 2022-05-26 12:38 UTC by ale-mazz

## Biometrics authentication

Closes: #11 

#### Alongside biometrics authentication the `rn-sensitive-info` has been replaced with `react-native-keychain` because the first one is not maintained anymore
If you can, test it with your Android device and check if everything is working properly. You will have to reimport your account with Ledger or with a Mnemonic passphrase

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed

2022-05-27 08:17 UTC, RiccardoM commented
I've tested it on my device and I have a couple of observations: 

1. Please insert a loading popup (or screen) while setting up the biometric authentication. On my device it takes ~1.5 second to complete and if there's no loading screen it seems that the app has frozen. 
2. While requesting the user to authenticate with the biometric info, I think we should display a different page below the biometric authentication popup. Right now the user sees the "Insert password" one, but I think another one with the app logo might be better instead

2022-05-27 15:06 UTC, ale-mazz commented
> 

Sounds good, i will update this pr with these features soon, thanks for your suggestions

2022-06-07 07:38 UTC, manu0466 requested changes
Seems that some changes have broken the visualization of the background behind the status bar on Android.
This may be caused by the changes into the `StyledSafeAreaView` component.

New version:
![image](https://user-images.githubusercontent.com/6245917/172322207-60bdcec3-1692-4568-83e8-435af8b7fc4c.png)
Previous version:
![image](https://user-images.githubusercontent.com/6245917/172322464-2f7d1f9a-a17c-4246-8208-240a266a9ded.png)

Also i will just change this text into "Authenticating", what do you think?
![image](https://user-images.githubusercontent.com/6245917/172322621-3015892a-cff9-4ceb-894f-95cf9b161be4.png)

2022-06-07 08:25 UTC, manu0466 approved these changes

2022-06-07 08:30 UTC, merged